# https://github.com/tuna/mirrorz/blob/9322a84bd4de97df39e5552f52b92a3eb740a0b7/.github/workflows/deploy.yml
name: Deploy to cloudflare pages
on:
  workflow_dispatch:
  push:
    branches:
    - docs
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ref: 'docs'
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Commit to another repository
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_REPOSITORY: ${{ secrets.PUBLISH_REPOSITORY }}
        run: |
          remote_repo="https://x-access-token:${ACCESS_TOKEN}@github.com/${PUBLISH_REPOSITORY}.git"
          remote_branch="docs"
          git_commit_id=$(git rev-parse --short HEAD)
          git config user.name "bot"
          git config user.email "bot@github"
          git remote add cf $remote_repo
          git push -u cf $remote_branch